version: 2

jobs:
  build_bundle:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: bundle check || bundle install
      - run: bundle exec jekyll build

  build_elm:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: sudo npm install -g elm
      - run: sudo npm install -g elm-test
      - run: elm make --yes
      # - run: elm test

workflows:
  version: 2
  build:
    jobs:
      - build_bundle
      - build_elm
